---
name: Greeting from Mona
on: push

jobs:
  Myjob:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 源碼
      uses: actions/checkout@v2
    - name: 設置 Python 環境      
      uses: actions/setup-python@v3

    - name: 升級 pip
      run: python -m pip install --upgrade pip

    - name: 安裝依賴
      run: pip install -r requirements.txt

    - name: 啟動 Python 服務器
      run: python3 server.py > log.txt 2>&1 &